version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: flask run --host=0.0.0.0 --port=5000 --debug

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
